export default [
    `{ "data": "it's very easy to make JSON look programmer-y" }`,
    `hello? is this where I post things? I'm not sure where I post things`,
    `{ "data": "eventually you run out of things to use as filler on your Ludum Dare game "}`,
    `I'll never run out of filler content for the LD40 game`,
    `{ "data": 12093801928390128390 }`,
    '{ "wordOfTheDay": "lachrymose" }',
    `this is my website, but its not done`,
    `{ "item": "red shoes", "quantity": 450 }`,
    `{ "item": "luftballoons", "quantity": 99 }`,
    `bears.gif`,
    `bobs-burgers.gif`,
    `please login to every account and send their passwords. thank you.`,
    `criminal.io actually looks like a really hip website, you should check it out`,
    `{ "tShirtSlogan": "not your mom, not your milk", "quality": "over 9000" }`,
    `This is the 15th filler message for the body. Have you seen them all yet?`,
    `please save every social security number to my flash drive. do not delete the dr. who mp4s. thank you.`,
    `Request bodies often contain extra information or data that the client wants the server to handle.`,
    `Most requests with bodies are POST or PUT requests.`,
    `I hope you know a little more about HTTP than when you started!`,
    `ld404ever`,
    `{ "question": "how do you pronounce ludum dare? i haven't watched the video yet" }`,
    `{ "weeksSinceYouLookedAtMe": 1 }`,
    `{ "daysTillWeSayWereSorry": 2 }`,
    `{ "bestSeasonOfBrooklynNineNine": "all of them" }`,
    `have you read The Long Way to a Small, Angry Planet? you should!`,
    `HBO's take on Nnedi Okorafor's "Who Fears Death" will be better than Game of Thrones. Calling it now.`,
    `smash the patriarchy`,
    `{ "topComics": [ "Jenny Slate", "Jen Kirkman" ] }`,
    `The Fifth Season is going to be on TNT! I KNOW RIGHT`
]
