<template>

    <section class="file-browser">
        <file-directory :tree="files"/>
    </section>

</template>

<script>
    export default {
        computed: {
            files () {
                let output
                try {
                    output = require(`@/gameplay/levels/level${this.$route.params.level}`).default
                } catch (err) {
                    output = ['autogenerated.html']
                }
                return output
            }
        }
    }
</script>

<style lang="scss">

    @import 'src/styles/vars';

    .file-browser {
        background-color: $right-bg;
    }

</style>
