<template>
    <div class="game-engine"></div>
</template>

<script>
    import Request from '@/gameplay/Request'
    export default {
        data () {
            return {
                scriptedEvents: [
                    require('@/gameplay/levels/level1').default,
                    require('@/gameplay/levels/level2').default
                ]
            }
        },
        mounted () {
            this.setupLevel()
        },
        methods: {
            setupLevel () {
                // Clear score, timer, all game files at start of new level
                this.$store.commit('RESET_BOARD')
                this.$store.commit('SET_MESSAGE', '')

                let output
                try {
                    output = require(`@/gameplay/levels/level${this.$route.params.level}`).default
                } catch (err) {
                    output = { files: ['autogenerated.html'] }
                }
                output.files.map(file => this.$store.commit('ADD_FILE', file))

                for (let i = 0; i < this.$route.params.step || 0; i++) {
                    this.$store.commit('INCREMENT_TOTAL_SUBMITTED')
                }
                if (!this.$route.params.step) {
                    setTimeout(() => {
                        this.$store.commit('ADD_REQUEST', this.currentScriptedEvents[0].req)
                    }, 1000)
                }
            }
        },
        computed: {
            currentScriptedEvents () {
                return this.scriptedEvents[this.$route.params.level - 1].requests
            },
            totalSubmitted () {
                return this.$store.state.totalSubmitted
            }
        },
        watch: {
            totalSubmitted (newVal) {
                // only on level 1
                // if (this.$route.params.level === '1') {
                setTimeout(() => {
                    if (this.currentScriptedEvents.length <= newVal) {
                        this.$store.commit('ADD_REQUEST', new Request())
                        return
                    }

                    this.$store.commit('ADD_REQUEST', this.currentScriptedEvents[newVal].req)
                        // Run any callbacks
                    if (this.currentScriptedEvents[newVal].callback) {
                        this.currentScriptedEvents[newVal].callback()
                    }
                }, Math.random() * 2000)
                // }
            },
            '$store.state.score' (newVal) {
                // only on level 1
                if (this.$route.params.level === '1') {
                    // covers 3 training rounds + 5 correct answers
                    if (newVal >= 8) {
                        this.$store.commit('SET_MESSAGE', 'Level complete!')
                    }
                }
            },
            '$route.params.level' (newVal) {
                this.setupLevel()
            }
        }
    }
</script>
